spring:
  datasource:
#    url: jdbc:h2:~/test
    url: jdbc:postgresql://localhost:5432/test
    driver-class-name: org.postgresql.Driver
#    username: sa
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
